# Cloud Build 스테이징 환경 배포 설정
# 트리거: develop 브랜치 푸시 시 자동 배포

steps:
  # Step 1: Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}-staging:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}-staging:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Step 2: 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}-staging'
    waitFor: ['build-image']

  # Step 3: 스테이징 환경에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-staging'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}-staging'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}-staging:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'ENVIRONMENT=staging,GCP_PROJECT_ID=${PROJECT_ID},GCP_REGION=${_REGION},USE_MOCK_VECTOR_DB=true,USE_MOCK_GRAPH_DB=true'
      - '--set-secrets'
      - 'GOOGLE_APPLICATION_CREDENTIALS=vertex-ai-key:latest'
    waitFor: ['push-image']

  # Step 4: 헬스체크
  - name: 'gcr.io/cloud-builders/curl'
    id: 'health-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME}-staging \
          --region ${_REGION} \
          --format 'value(status.url)')
        echo "Staging URL: $SERVICE_URL"
        sleep 10
        curl -f $SERVICE_URL/health || exit 1
    waitFor: ['deploy-staging']

timeout: '1200s'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'us-central1'
  _REPOSITORY: 'ai-agent'
  _SERVICE_NAME: 'ai-agent-api'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}-staging:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}-staging:latest'
